# Generated by Django 2.2.1 on 2019-05-27 09:19

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=30, verbose_name='родител')),
                ('child', models.CharField(max_length=30, verbose_name='дете')),
                ('school', models.CharField(max_length=50, verbose_name='училище')),
                ('group', models.CharField(choices=[('I', 'Първи клас'), ('II', 'Втори клас'), ('III', 'Трети клас'), ('IV', 'Четвърти клас'), ('P', 'Предучилищна')], max_length=1, verbose_name='клас')),
                ('period_from', models.DateField(verbose_name='от')),
                ('period_to', models.DateField(verbose_name='до')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='поща')),
                ('extra', models.TextField(blank=True, null=True, verbose_name='допълнително')),
            ],
            options={
                'verbose_name': 'заявление',
                'verbose_name_plural': 'заявления',
            },
        ),
    ]
