# Generated by Django 2.2.1 on 2019-05-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20190528_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childapplication',
            name='igralnica',
        ),
        migrations.RemoveField(
            model_name='childapplication',
            name='zanimalnica',
        ),
    ]
