# Generated by Django 2.2.1 on 2019-05-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20190528_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='childapplication',
            name='type',
            field=models.CharField(choices=[('I', 'Игралница'), ('Z', 'занималница')], default='I', max_length=1, verbose_name='тип'),
            preserve_default=False,
        ),
    ]
