# Generated by Django 2.2.1 on 2019-05-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20190528_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childapplication',
            name='type',
        ),
        migrations.AddField(
            model_name='childapplication',
            name='type',
            field=models.CharField(choices=[('I', 'Игралница'), ('Z', 'Занималница')], default='I', max_length=2, verbose_name='тип'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
