# Generated by Django 2.2.1 on 2019-05-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20190528_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childapplication',
            name='type',
            field=models.BooleanField(choices=[('I', 'Игралница'), ('Z', 'Занималница')], verbose_name='тип'),
        ),
    ]
