# Generated by Django 2.2.1 on 2019-05-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20190528_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childapplication',
            name='type',
            field=models.CharField(choices=[('I', 'Игралница'), ('Z', 'Занималница')], max_length=2, verbose_name='тип'),
        ),
    ]
