# Generated by Django 2.2.1 on 2019-05-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_auto_20190528_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childapplication',
            name='type',
        ),
        migrations.AddField(
            model_name='childapplication',
            name='igralnica',
            field=models.BooleanField(default=False, verbose_name='тип'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='zanimalnica',
            field=models.BooleanField(default=False, verbose_name='тип'),
        ),
    ]
