# Generated by Django 2.2.1 on 2019-05-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20190528_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childapplication',
            name='igralnica',
        ),
        migrations.AddField(
            model_name='childapplication',
            name='type',
            field=models.CharField(choices=[('I', 'Игралница'), ('Z', 'Занималница'), ('B', 'Игралница-Занималница')], default='B', max_length=1, verbose_name='тип'),
            preserve_default=False,
        ),
    ]
