# Generated by Django 2.2.1 on 2019-05-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_auto_20190528_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childapplication',
            name='zanimalnica',
        ),
    ]
