# Generated by Django 2.1.8 on 2019-05-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_remove_childapplication_zanimalnica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childapplication',
            name='group',
            field=models.CharField(choices=[('1', 'Първи клас'), ('2', 'Втори клас'), ('3', 'Трети клас'), ('4', 'Четвърти клас'), ('P', 'Предучилищна')], max_length=1, verbose_name='клас'),
        ),
        migrations.AlterField(
            model_name='childapplication',
            name='type',
            field=models.CharField(choices=[('I', 'Лятна Игралница'), ('Z', 'Лятна Занималница'), ('B', 'Игралница-Занималница')], default='B', max_length=1, verbose_name='тип'),
        ),
    ]
