# Generated by Django 2.1.8 on 2019-05-31 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('applications', '0013_auto_20190531_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildApplicationPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='applications_childapplicationpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.ChildApplication')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
