# Generated by Django 2.2.1 on 2019-05-27 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No title', max_length=50, verbose_name='заглавие')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='дата на публикуване')),
                ('content', models.TextField(default='No content', verbose_name='съдържание')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'публикации',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=640, verbose_name='съдържание')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='дата на създаване')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcomments', to='news.Post', verbose_name='публикация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucomments', to=settings.AUTH_USER_MODEL, verbose_name='потребител')),
            ],
            options={
                'verbose_name': 'коментар',
                'verbose_name_plural': 'коментари',
            },
        ),
    ]
