# Generated by Django 2.2.1 on 2019-05-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заглавие')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Дата на публикуване')),
                ('content', models.TextField(verbose_name='Съдържание')),
            ],
        ),
    ]
