# Generated by Django 2.2.1 on 2019-05-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Update',
        ),
    ]
