# Generated by Django 2.2.1 on 2019-05-09 00:02

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
        ('news', '0002_auto_20190505_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='pictures.Album', verbose_name='албум'),
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='gallery/<django.db.models.fields.related.ForeignKey>', verbose_name='снимка'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='съдържание'),
        ),
    ]
