# Generated by Django 2.2.1 on 2019-05-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190502_1543'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Update',
            new_name='Post',
        ),
    ]
