# Generated by Django 2.2.1 on 2019-05-09 00:54

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190509_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='gallery/None', verbose_name='снимка'),
        ),
    ]
