# Generated by Django 2.2.1 on 2019-05-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childapplication',
            name='period_from',
            field=models.DateField(verbose_name='от'),
        ),
        migrations.AlterField(
            model_name='childapplication',
            name='period_to',
            field=models.DateField(verbose_name='до'),
        ),
    ]
