# Generated by Django 2.2.1 on 2019-05-27 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChildApplication',
        ),
    ]
