# Generated by Django 2.2.1 on 2019-05-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190518_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childapplication',
            name='user',
        ),
    ]
