# Generated by Django 2.2.1 on 2019-05-22 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_childapplication_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childapplication',
            options={'verbose_name': 'заявление', 'verbose_name_plural': 'заявления'},
        ),
    ]
