# Generated by Django 2.2.1 on 2019-05-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заглавие')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='дата на създаване')),
                ('is_visible', models.BooleanField(default=True, verbose_name='публичен')),
            ],
            options={
                'verbose_name': 'албум',
                'verbose_name_plural': 'албуми',
            },
        ),
    ]
