# Generated by Django 2.2.1 on 2019-05-27 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заглавие')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='дата на създаване')),
                ('is_visible', models.BooleanField(default=True, verbose_name='публичен')),
            ],
            options={
                'verbose_name': 'албум',
                'verbose_name_plural': 'албуми',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='common/static/gallery/', verbose_name='снимка')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='дата на качване')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='pictures.Album', verbose_name='албум')),
            ],
            options={
                'verbose_name': 'снимка',
                'verbose_name_plural': 'снимки',
            },
        ),
    ]
