# Generated by Django 2.2.1 on 2019-05-12 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='common/static/gallery/', verbose_name='снимка')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='дата на качване')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='pictures.Album', verbose_name='албум')),
            ],
            options={
                'verbose_name': 'снимка',
                'verbose_name_plural': 'снимки',
            },
        ),
        migrations.CreateModel(
            name='PictureComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=640, verbose_name='съдържание')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='дата на създаване')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_comments', to='pictures.Picture', verbose_name='снимка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_comments', to=settings.AUTH_USER_MODEL, verbose_name='потребител')),
            ],
            options={
                'verbose_name': 'коментар',
                'verbose_name_plural': 'коментари',
            },
        ),
    ]
