# Generated by Django 2.2.1 on 2019-05-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190508_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='common/static/avatars/default.jpg', upload_to='common/static/avatars/', verbose_name='аватар'),
        ),
    ]
