# Generated by Django 2.2.1 on 2019-05-08 15:09

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190508_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='common/static/avatars/default.jpg', upload_to='common/static/avatars/', verbose_name='аватар'),
        ),
    ]
